AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'
    - 'db/migrate/**/*'
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: False

Style/RedundantSelf:
  Enabled: False

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/api/**/*'
    - 'app/controllers/users/oauth_email_confirmations_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/oauth_callbacks_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/oauth_callbacks_controller.rb'
    - 'app/controllers/users/oauth_email_confirmations_controller.rb'
    - 'app/services/find_for_oauth.rb'
